### ISSUE TITLE
Which design for doc page

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#11]
Some sample designs for the doc page:

1. https://formik.org/docs/overview
2. https://react-redux.js.org/introduction/getting-started
3. https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/creating-and-editing-milestones-for-issues-and-pull-requests

Please write your opinion what you like/dislike about each design, and:

1. Which font style is better: 1 or 3?
2. Which layout style is better
3. Which font size is better

**Comment by aminsaedi** [comment]
In terms of layout style I think the first one is better for this project because we links at the root level as same as Formik style but others only have expandable items at root
and for font size and style the react-redux style is more readable than others

**Comment by pmvald** [comment]
sg, for left toc sidebar we follow formik site: only subsections need to be expandable
