### ISSUE TITLE
Tab shortcode - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#18]
We need an mdx shorcode component for tabbed boxes, similar to one you see here:

https://cloud.google.com/firestore/docs/query-data/listen

(see the box with tabs "Web version 9", "Web version 8", ...) - For now we don't need styling, just a bordered box with two sections: 1. tabs bar, 2. the current tab body

tab body could be any other mdx (I will usually use it for code, so it should be mdx, not md - md has limitations for highlighting ...)

Feel free to use any react library for the tab - you need to wrap the tab body inside another component

Question: check the Gatsby plugin for mdx, I think it should allow us to apply the mdx compiler to the shortcode's body as well, it's a very common task - maybe we don't need an extra wrapper like markdown-js, etc

**Comment by aminsaedi** [comment]
Any updates?

**Comment by pmvald** [comment]
Done!
