### ISSUE TITLE
Responsiveness for the doc page - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#20]
Before doing this task make sure you understand our design system, explained in the README file of [this repo](https://github.com/pmvald/sss); and this repo itself also contains an example of such design system which you can use as starting point

I already made a branch for this task called "feature/doc-page-responsiveness" with some starter files in it. Please checkout this branch after cloning

We want to design a responsive system for our doc page.

Note that our doc page consist of three columns: left sidebar, body, right sidebar

I made a starter page at `src/__mocks/doc-page-res.tsx` to show these three columns (once you start the Gatsby dev server access this page at `http://localhost:8000/__mocks/doc-page-res`)

In the mobile view we want to:
1. hide the left and right sidebars
2. show the toggle button (in the header)
3. clicking the toggle button will cause the left sidebar to fly in from left side onto the screen

(to see an example see https://angular.io/guide/interpolation)

Note that I wrote react code so that upon clicking the toggle button a class called "show-left-sidebar" will be added to the wrapper element. feel free to change its name.

Your design should be just css. You may define your css in the `style` object defined on the top of the file (the flying effect should be also based on css animation)

Feel free to change the html layout (probably you need to emulate the Modal layout in bootstrap ....)

NO NEED TO STYLE ANYTHING. Just add css styles enough to implement the function (i.e., changing the layout in mobile view as explained in the above 3 points) - We have another Peron working on the UX/UI design to adjust the fonts, colors, etc. So you just make responsive ...

Note: you can also define your css classes in a css (or scss) in the same folder as the tsx file and then just import it into the tsx file, then you will have all the classes in your tsx file. So feel free to add a scss or css file as well. 

For now just use prefix `ss-` for your class names (layer 2)

**Comment by yuki-tylar** [comment]
I updated the branch using css only
* browser width >= 768 ==> always show 3 cols. hide toggle button
* browser width < 768 ==> show toggle button and show / hide leftSideBar with css animation
      !!state ==> overlay leftSideBar
      !state ==> hide leftSideBar
