### ISSUE TITLE
Generating headers list to be used in the doc page right sidebar - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#23]
Probably using some remark or rehype plugins, see:
- https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/?=mdx#remark-plugins
- https://github.com/remarkjs/remark/blob/main/doc/plugins.md

Hint: after installing plugins, to see the graphQl nodes start teh dev server and go to: `localhost:8000/___graphQl` - check the nodes and see which one has the data you want - as you do that the graphQl query is also generated for you in the middle window

**Comment by aminsaedi** [comment]
Can. you please explain it a little bit more?

**Comment by pmvald** [comment]
We basically want to generate the right sidebar contents, which is anchor link to the body `h2` elements (see the right sidebar of sample doc pages mentioned in [this issue](https://github.com/pinglue/site/issues/3)). 

The starting point is `/src/pages/{mdx.slug}.tsx` file. This file gets the mdx data through a graph ql query at line 21 (btw you can see the result of these graph ql queries once you start the dev server at `localhost/___graphQl` - you can also build queries there - that's how I made these queries) - right now our graphQl uses the endpoint `mdx` which provides us with such data as frontmatter, slug, body, etc.  What we also want is a list of h2 elements in the body. How to get them? Several options:

1. parse the body field (compiled mdx) directly - which is not a good idea
2. adding some remark plugin to the Gatsby mdx plugin (guide: https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/?=mdx#remark-plugins) - the remark plugins are supposed to add more data to the mdx endpoint, so if you choose the right plugin we might have an additional field (like `headers`) in the mdx endpoint in addition to slug, body, etc

Either way, I feel this is a very common task and there must a plugin for that, we should not write any code to get a list a headers. If you couldn't find such a plugin or any easy way let me know and we'll figure out to revise the task (I assumed it's an easy task, but could be more complicated if we couldn't find any pre-made plugin ...)

Once you get a list of headers you can pass them to the DocPage component, and that component also passes it down to a new PageHeadersBar (or any other name) which renders the right sidebar (the headers must also link to the headers in the page ...)

See how we an do this task
