### ISSUE TITLE
Design for doc page (html/css) - 2x

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#3]
New update: ========================================================

We want to design a sample doc page at `src/pages/__mocks/sample-doc-page.tsx`

We decided to follow the layout of [option 3](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/creating-and-editing-milestones-for-issues-and-pull-requests), namely :

1. a left sidebar (table of contents) going all the way up and containing the page logo and title
2. body column with a header containing breadcrumb followed by two columns: 1-body, 2-right sidebar for page headers anchors

Font and style mainly follow [option 1](https://formik.org/docs/overview) and maybe [option 2](https://react-redux.js.org/introduction/getting-started) if you see fit.

We follow the design system as described in the README file. You can have the layer 0 and layer 1 scss files at `src/scss` (you can copy/paste from the original sss repo mentioned in the README file) - for layer 2 styles, you may keep them in `src/scss` as well or in the same folder as the component file (apparently since we are using react it is better to keep the layer 2 styles which are mostly component specific in the same folder as component itself ...) - You may refer to branch `feature/initial-scss-importing` for a sample importing of styles into `src/scss`; but this is not a good example as it imports all the styles from the sss repo here, we may just need layer 0 maybe, and other layers have to be written again by us. But of course we can use the sss repo styles as starting point but should not be copied and pasted as such.

There is also an unfinished html mock sample at branch `feature/initial-scss-importing` (src/pages/__mocks) that you can optionally choose as your starting point, but feel free to start your own design if we feel more comfortable (the one in this branch does not follow the design system closely, so you will need to rename/reformat many of the the styles anyway ...) 

Original description begins: =================================

Candidate samples (the team will vote which ones to follow):
1. https://formik.org/docs/overview
2. https://react-redux.js.org/introduction/getting-started
3. https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/creating-and-editing-milestones-for-issues-and-pull-requests

Number 1 and 2 are samples of a standard doc page (1 has better over layout, 2 has better font), 3 has better Toc left sidebar that contains the doc title  as well.

Components:
- header (if any)
- doc title section
- Toc
- main body
- footer

Responsive design

**Comment by pmvald** [comment]
Yes please, make any change that makes sense. We will change during project even more. But commit an initial version of it so that other people can also get started. We will make modifications together.

Sent from Yahoo Mail on Android 
 
  On Wed., 12 Jan. 2022 at 1:40 p.m., ***@***.***> wrote:   


Dear Peter, Can I hide some css class from layout? for example in styles/reboot, we have a class for img which set width:100%.
I want to use an image for logo and don't need to use "reboot" class, Can I Hide it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pmvald** [comment]
The UI itself looks good; some more points:

1. The width of left sidebar is too narrow. There is usually standard size for TOC sidebar, you can refer to the sample websites I sent
2. Left sider bar should scroll if list is large. To demostrate this increase the size of TOC
3. Add some subsections (with expand/collapse icon, you can use Bootstrap icons which are already included in our design system
4. doc pages have standard padding for sidebars and the body sections, refer to the samples and adjust them (present paddings are not right
5. Use "Lorem Ipsum" text to fill the paragraphs: https://www.lipsum.com/
6. We need right sidebar as well (page TOC)

In the future you need to figure out all the details above. For html/css design one or two commits should be enough, we don't want to spend lot of time discussing and me typing these things (for otherwise I can do it myself with less time) - so follow all the details and push a complete work

**Comment by pmvald** [comment]
Also adding to above details:
7. For body section we need a header with breadcrumb on left and a github icon on right (follow the Github sample I sent you and we discussed)

**Comment by dara2021** [comment]
I did things, but:
1- for the last ( header with breadcrumb on the left and icon on the right), will I remove icon in sidebar and add icon in header?
2-I push my latest commit but cannot create pull request, Can you help me?  @pmvald

**Comment by pmvald** [comment]
@yuki-tylar  I assigned this task to you - it is half done ...

**Comment by yuki-tylar** [comment]
@pmvald 
I guess dara2021 was working at some branch (maybe `feature/initial-scss-importing`?) Should I start coding using the branch or did you already merge some changes to main?

**Comment by pmvald** [comment]
Yes, you can start a new branch. But you can use the materials at branch initial-scss-importing if you want. That was a raw mock for our design ideas.

Sent from Yahoo Mail on Android 
 
  On Mon., 17 Jan. 2022 at 11:20 p.m., ***@***.***> wrote:   


@pmvald
I guess dara2021 was working at some branch (maybe feature/initial-scss-importing?) Should I start coding using the branch or did you already merge some changes to main?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuki-tylar** [comment]
Sure, then I will...
* create new branch from main and copy some style files from the branch `initial-scss-import`
* import `TocComponent` to `DocPageRes` (maybe need to edit TocComponent)
* create some components such as `docTitle` / `header` / `mainBody` / `footer` and import to `DocPageRes`
* make leftSidebar scrollable (using `stickyPosition` could be solution)

**Comment by yuki-tylar** [comment]
@pmvald 
I pushed some changes (not completed yet)
branchName: yuki-tylar/issue3 (https://github.com/pinglue/site/tree/yuki-tylar/issue3)
Can you please quick review if I'm doing something wrong?

* imported css and iconFont from `sss` and imported in `Gatsby-browser`
* put toc in leftBar and made it scrollable
* add sticky header on top of body and rightBar
* add GitHub icon (not linked yet)

If I'm doing right, I will ...
* create several component such as docTitle / header / mainBody / footer
* use real logo instead of Gatsby logo
* add loremIpsum
* add breadcrumb

**Comment by pmvald** [comment]
I left comments for the commit

**Comment by yuki-tylar** [comment]
* import `scss` folder from `sss`  and comment out some sass files for `layer 2` which are not necessary for now
* delete css which i imported from sss at last commit
* create components such as `Header`, `DocTitle`
* add dummy content in body
* stylyze `h1` - `h6` & `s-contents`

**Comment by yuki-tylar** [comment]
@pmvald 
* Should I hide rightSideBar because it makes body width too narrow at tabletView?
* Should I add more style such as `code` `pre` in `s-contents`?

**Comment by pmvald** [comment]
Yes to both!

Sent from Yahoo Mail on Android 
 
  On Wed., 19 Jan. 2022 at 11:54 p.m., ***@***.***> wrote:   


@pmvald
   
   - Should I hide rightSideBar because it makes body width too narrow at tabletView?
   - Should I add more style such as code pre in s-contents?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuki-tylar** [comment]
@pmvald 

### rightSidebar
* browserWidth < 992px: show under mainBody
* 992px <= browserWidth: show right side

### code box
designed completed
also you can scroll inside the box
