### ISSUE TITLE
Add global states to doc pages - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#34]
1. tab number for tabs with the same id (on tan change -> all change)
2. current frame work name
3. ... more

**Comment by aminsaedi** [comment]
I'm doing it.
what is your opinion about adding redux to the project?

**Comment by pmvald** [comment]
Maybe I forgot to mention, but you should refer to the [project page](https://github.com/orgs/pinglue/projects/1) to see which project you have to start with (the one in the middle column) - Assigning does not mean that the task is ready yet- Once the task becomes ready we move it to the middle column (in-progress) and then you can start. We also usually have one in-progress task per person, so that we do the tasks one by one

For now I moved this task to in-progress column as I merged the previous one.

Yes, we need to use redux - here is a more detailed explanation of what we need to do in this task:

You remember the <Tab> we made in previous task. Most of the time we have multiple tabs in one page and all of them have the same tabs - we want them to be in sync. So if user changes tab option in one Tab component, all other tabs in that page also change. We usually use tab options for languages/frameworks, so when a user chooses a framework we want to change all the tabs to show information for that framework.

Also adding to the above paragraph, we want the tab options to be scoped by the "document" not the page actually (remeber right now we have two docs: pinglue and pgweb) - so for example when user goes to a page in pgweb doc and chooses a tab option "A", then all the tabs in pgweb doc should be sinced to option A.

But what if we want to have a Tab that is different from others? To solve this problem we assign a tabId prop to the Tab component. All the tabs with the same tabId should be synced with each other throughout a document. You can assume that all the tabs with the same tabId have the exact same tab options. 

This cannot be done easily with context (since context is mainly for a parent to command a descendant) - in this case we need a reducx store and you can keep state of tabs by their document name and tabId.
