### ISSUE TITLE
Doc cross link

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#35]
Find a method; ideally: we assign a friendly id to each doc, and can link to it from other docs (so links don't get broken when url is changed)

More precisely, in the front matter of mdx file we want to add an id field:

```
---
title: Installing Pinglue packages
id: installing-packages
---
```

And then in a different mdx we want to ues the id to link to this page:

```
For more info refer to <Link href="id:installing-packages">this article<Link>
```

here, the href starts with "id:" which indicates that the link is an id of another page and it has to be converted. If the href does not start with *id:* then it is treated as regular link and has to be convrted to Gatsby Link (if href is local; meaning it starts with `/` or any name) or `<a>` (if href is external, meaning it starts with `http`)

Suggestions: search among Gatsby plugins, there must be some ready plugins for this purpose ... If not we have to write our own shortcode `Link` ...

lets discuss here

**Comment by aminsaedi** [comment]
what do you think about this plugin?
https://github.com/cedricdelpoux/gatsby-plugin-slug
it's not convert id to relative path like `/doc/pingule/...` it generates a unique url for each doc if we add `slug` field to each doc
for example if we have
```
---
title: Topic 1
slug: my-custom-slugs
---
```
then there is page: `pingule.com/my-custom-slug`
I dont think that it's useful
we have to generate our link component

**Comment by pmvald** [comment]
For slugs we just follow the filesystem, otherwise there would be lot of conflicts ... We just need a shortcut for some frequently used pages. You can create a shortcode component `<Link>` and use a static Graph QL query similar to the one in Toc component to get a list of all pages in the doc (and reformat it if need be) - then based on href value decide the final url value:

1. if href value starts with ":id" then use the static data you got from graph ql to figure out the actual slug of the page with the given id
2. if href starts with "http" then just render a regular `<a>` link
3. otherwise treat it as a local page and use Gatsby's `<Link>` to have a link with frontend-router navigation
