### ISSUE TITLE
Followup bug with mock doc page

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#41]
Related to task: https://github.com/pinglue/site/issues/3

So now the page is styled and looks nice.  A few problem with a the layout though. 

1. I made some changes to the ss-doc-wrapper css to limit its width, and now the body column seems to keep its width if we make the window smaller ... see how to make the body column adjust its width - the problem could be from the grid system. I found it a bit complicated. Maybe you can simplify it and the problem will be solved? I didn't review the grid structure carefully but potentially could be from there. The simplest design is to make the ss-doc-wrapper a grid with two columns: 1. left sidebar, 2- the rest, then make the rest having a header and a body , and this body is a grid with two columns (doc-wrapper__body and doc-wrapper__right-sidebar) - either ways, it is up to you to determine the grid system, but keep it simple and also resolve this bug

2. we need the famous `<meta name="viewport" content="width=device-width, initial-scale=1">` some where in the page meta - you can use Helmet component for that.

**Comment by yuki-tylar** [comment]
Sure, I think grid design is not good fit for this layout.
Here is solution
```
DocWrapper.row
  LeftSideBar.col (flex: 0 0 300px)
  MainViewWrapper.col (flex: 1 0 auto)
    Header
    MainView.row
      Body.col (flex: 1 0 auto)
      RightSideBar.col (flex: 0 0 300px)
```
I guess this is the simplest way to make this layout.
if I do this, Body width can be maximized and child elements are rendered as we want.

**Comment by pmvald** [comment]
> Sure, I think grid design is not good fit for this layout. Here is solution
> 
> ```
> DocWrapper.row
>   LeftSideBar.col (flex: 0 0 300px)
>   MainViewWrapper.col (flex: 1 0 auto)
>     Header
>     MainView.row
>       Body.col (flex: 1 0 auto)
>       RightSideBar.col (flex: 0 0 300px)
> ```
> 
> I guess this is the simplest way to make this layout. if I do this, Body width can be maximized and child elements are rendered as we want.

Sounds good, keep it simple!

**Comment by yuki-tylar** [comment]
Switched to flexbox from grid.

But the issue was still there. the root cause was `<pre><code></code></pre>`
if `code` width is bigger than screen size, the page width cannot fit to browser width because of `flexbox` (and maybe grid as well) even if  `overflow: hidden` is applied to `pre`. (which is weird...)

To solve this, I applied `width: 0` to `code`.

**Comment by pmvald** [comment]
Sounds good. When you are done request a review for the pull request and I'll merge
