### ISSUE TITLE
Mobile view touchups - 10%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#49]
1. Make the hamburger buttom a bit bigger and more clear
2. hide github icon (and all the right side part contents), we only show the breadcrumb

**Comment by yuki-tylar** [comment]
2) Do you want to hide this part?

![Screen Shot 2022-01-22 at 11 14 47 PM](https://user-images.githubusercontent.com/32935311/150668528-7a1eb805-84e0-415b-ac15-2f491e5ef567.png)

**Comment by pmvald** [comment]
> 2. Do you want to hide this part?
> 
> ![Screen Shot 2022-01-22 at 11 14 47 PM](https://user-images.githubusercontent.com/32935311/150668528-7a1eb805-84e0-415b-ac15-2f491e5ef567.png)

Yes, should be! - Also please add a "Edit this page" link to the right side of the bread crumb (like [this doc](https://mui.com/getting-started/usage/)) For mobile view only show the icon. Don't worry about the link itself, we'll add it later dynamically for each page to link to the page doc source on Github

**Comment by yuki-tylar** [comment]
* removed github icon
* made hamburger menu bigger using s-icon-btn (also changed s-icon-btn fontSize from 30 to 24 because it was too big)
* adjusted layout to make hamburger menu and close button sit at same position.
* removed unnecessary styles
