### ISSUE TITLE
Dismissible notice bar - 10%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#51]
pretty much same as bootstrap alert which also hasa dismiss button ... just has to be renamed to `s-alert` ...

**Comment by yuki-tylar** [comment]
I modified `Notice` to make it dismissible optionally.
Or do you want to use bootstrap alert?

**Comment by pmvald** [comment]
Yes that works too. But we want to use this type of notice on the too of the page (think about COVID alerts that you see on top of pages), we we also need to make the icon, title and the text in the same line. So you can also add an option to Notice component to bring the icon and title inline with the message. 

Sent from Yahoo Mail on Android 
 
  On Sat., 29 Jan. 2022 at 1:32 p.m., ***@***.***> wrote:   


I modified Notice to make it dismissible optionally.
Or do you want to use bootstrap alert?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuki-tylar** [comment]
I modified the branch
* added inline option so that you can show title / icon / message in same line.
* give more flexibility so that you can customize icon / title.
