### ISSUE TITLE
Reformating slug

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#56]
Remove initial index number:

docs/01-section/02-topic --> docs/section/topic

**Comment by aminsaedi** [comment]
should I change it to something like this?
```
/pgweb
     topicOne.mdx
     topicTwo.mdx
     /sectionOne
          topicOne.mdx
          topicTwo.mdx
          /subSectionTwo
               topicOne.mdx
               topicTwo.mdx
.
.
.    
```

**Comment by pmvald** [comment]
Yes for sure - btw, I merged several PRs, so please update your branch before pushing
