### ISSUE TITLE
headerList html semantic

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#69]
Should be 

```
<aside> 
  <ul>
    <li>
```

**Comment by AjRadwan** [comment]
If this issue isn't solved do tell me if there is any need for more changes

**Comment by pmvald** [comment]
Yes you can go ahead and make PR. In general the issues which are not assigned to anyone are open for whoever want to work on them. 

This is a good starter task. FYI, the reference for html semantics is summerized in *Web standard* section of [this doc](https://appers-lab.com/guides/design-system) - it makes the html code more pro!
