### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by SJellen** [pinglue/site#73]
Dead link in readme

<img width="714" alt="Screen Shot 2022-01-30 at 8 43 50 AM" src="https://user-images.githubusercontent.com/51421669/151702324-42d170d1-648d-4fbf-b2d8-61f4894ff333.png">

**Comment by AjRadwan** [comment]
Hello @pmvald  How should I fix this issue? should I remove the link or where can I find a link for this that actually works.

**Comment by pmvald** [comment]
Yes, that link is for org members only. If you are not a member you will get error. I mentioned that in the doc
