### ISSUE TITLE
Logo wanted

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#74]
Logo for Pinglue framework - preferable svg - have some ideas, ask me!

**Comment by Divyansh1315** [comment]
Hey!! What kind of logo do you need. Can you please elaborate because I'm interested in this issue.

**Comment by pmvald** [comment]
Very simple one. You see the main keyword for our tools is *pg*, so the logo is based on that. Here is a rough sketch:

![logo](https://user-images.githubusercontent.com/31361906/152703164-84ff48dd-989a-47bb-9162-3765ee831202.png)

So basically two circles (from p and g) and it kind of looks like a face. Up to the artist to figure out the details. It should transparent background. The color for it is `#123abc` ;)

**Comment by Divyansh1315** [comment]
Do you mind If I give it a try?

**Comment by pmvald** [comment]
Sounds good. Go ahead. See if you can make it into SVG format, it is even better.

Sent from Yahoo Mail on Android 
 
  On Sun., 6 Feb. 2022 at 9:46 p.m., ***@***.***> wrote:   


Do you mind If I give it a try?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Divyansh1315** [comment]
Hey I've created something would you like to see?

**Comment by Divyansh1315** [comment]
I've created a pull request. Kindly review it. I'm open for discussion on any kind of changes if you want or want me to ad something on it
Thank you for giving me this opportunity.
